SDK-1133: Retrieve the same attribute with different constraints
getyoti/ruby pull request #76
Opened 2019-11-29 11:18 UTC by emmas-yoti

Add get_all_attributes_by_name(string):array to return a list of
attributes sharing the same attribute name.

2019-11-29 15:48 UTC, echarrod approved these changes
Looks good, let's wait to test on the example project before merging though 👍

2019-12-02 11:07 UTC, davidgrayston requested changes
I think there's a breaking change in here _(although it's unlikely anyone would be instantiating a profile themselves)_

2019-12-02 11:07 UTC, davidgrayston commented on lib/yoti/data_type/base_profile.rb
> +    def attributes
Do we also need `def attributes_list` (or similar) that would return the full list of `Array<Yoti::Attribute>` like other SDKs?

2019-12-02 11:07 UTC, davidgrayston commented on spec/yoti/data_type/profile_spec.rb
> +    [name, [Yoti::Attribute.new(name, value, {}, {})]]
This indicates a breaking change (although a low risk one)

2019-12-03 15:30 UTC, emmas-yoti commented on lib/yoti/data_type/base_profile.rb
>      # @param [Hash{String => Yoti::Attribute}] profile_data
I don't think @attributes can be a Hash of Objects any more? It's always set with a Hash-of-list?

2019-12-03 15:31 UTC, emmas-yoti commented on lib/yoti/data_type/base_profile.rb
>      # @param [Hash{String => Yoti::Attribute}] profile_data
Oh, wait this isn't a constructor.

2019-12-03 15:52 UTC, davidgrayston commented on lib/yoti/data_type/base_profile.rb
>      # @param [Hash{String => Yoti::Attribute}] profile_data
Sorry, I meant comment this to correspond with line 18

I was thinking you could provide a `Array<Yoti::Attribute>` and process this into both a `[Hash{String => Array<Yoti::Attribute>}]` and `[Hash{String => Yoti::Attribute}]` (for backwards compatibility).

(but you'd also have to support `[Hash{String => Yoti::Attribute}]` being passed into the constrictor as before, so a bit fiddly)

2019-12-05 18:37 UTC, davidgrayston approved these changes

2025-05-16 11:48 UTC, closed without merging